#!/bin/bash

# Description: This script orchestrates the execution of multiple data
# processing and analysis tasks.  It primarily involves running the
# 'tablegenerator' and 'extract' executables with various
# configuration files and parameters, generating data files, and
# performing sorting operations.  It also utilizes the 'genPlot.sh'
# and 'pre_sort.sh' scripts for plotting and performance analysis.
# The script is designed to generate a comprehensive set of results
# and metrics for performance evaluation and comparison of the 37
# algorithms of the DGS study and of the three algorithms described in
# the paper.
#
# Workflow:
# 1. Runs 'tablegenerator' with different configuration files (conf_*)
#    to generate tables of metrics.
# 2. Runs 'extract' to extract specific data from summary files based
#    on input files and parameters.
# 3. Runs 'genPlot.sh' to generate data files for plotting performance
#    curves.
# 4. Runs 'pre_sort.sh' to analyze and pre-sort data based on
#    different subset sizes.
# 5. Cleans up temporary files (sparse.txt).
#
# Dependencies:
#   - build/tablegenerator: An executable for generating tables of metrics.
#   - build/extract: An executable for extracting data from summary files.
#   - scripts/genPlot.sh: A script for generating data files for plotting.
#   - scripts/pre_sort.sh: A script for pre-sorting data.
#   - data/conf_*: Configuration files for 'tablegenerator'.
#   - data/summary_DGS.csv: A summary data file for 'extract'.
#   - data/DGS_interesting.txt, data/DGS_hard.txt: Input files for 'extract'.
#
# Output:
#   - Various data files in the 'results/' directory (e.g.,
#     DGS_interesting.txt, 20neg.txt, 50neg.txt).
#   - Data files for plotting generated by 'genPlot.sh'.
#   - Pre-sorted data files generated by 'pre_sort.sh'.
#   - Table data generated by 'tablegenerator'.
#
# Usage:
#   - bash make_all.sh (runs all the steps)

if [[ ! -d results ]]; then
    mkdir results
fi

build/tablegenerator -p data/conf_interesting -d results/DGS_interesting.txt
build/tablegenerator -p data/conf_interesting2 -d results/DGS_interesting2.txt
build/tablegenerator -p data/conf_Table4SM
build/tablegenerator -p data/conf_Table1
build/tablegenerator -p data/conf_Table2
build/extract -s data/summary_DGS.csv -o sparse.txt -i data/DGS_interesting.txt -d 3
build/tablegenerator -p data/conf_Table3
rm -f sparse.txt
build/tablegenerator -p data/conf_Table9SM
build/tablegenerator -p data/conf_Table4
build/tablegenerator -p data/conf_hard -d results/DGS_hard.txt -l 0
build/tablegenerator -p data/conf_Table5
build/extract -s data/summary_DGS.csv -o results/20neg.txt -i data/DGS_interesting.txt -n 20
build/tablegenerator -p data/conf_Table7SM
build/extract -s data/summary_DGS.csv -o results/50neg.txt -i data/DGS_interesting.txt -n 50
build/tablegenerator -p data/conf_Table8SM
bash scripts/genPlot.sh data/conf_Figures78 10 1
bash scripts/genPlot.sh data/conf_Figures78 10 4
bash scripts/pre_sort.sh 119
bash scripts/pre_sort.sh 264
bash scripts/pre_sort.sh 527
bash scripts/pre_sort.sh 862
bash scripts/pre_sort.sh 1317
build/tablegenerator -p data/conf_Table11SM
build/tablegenerator -p data/conf_Table12SM
build/tablegenerator -p data/conf_Table13SM
build/tablegenerator -p data/conf_Table14SM
build/tablegenerator -p data/conf_Table8
build/tablegenerator -p data/conf_Table9
build/tablegenerator -p data/conf_Table17SM
build/tablegenerator -p data/conf_Table10
build/tablegenerator -p data/conf_Table19SM -a
build/tablegenerator -p data/conf_Table20SMa -r results/DGS_NN_best.txt -c NN-SSS -m 1
build/tablegenerator -p data/conf_Table20SMb -a
